# Basic
title: 雨水
subtitle: 时间是一切财富中最宝贵的财富！
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Welcome Everybody</a>
welcome_message: <a target="_blank">Welcome Everybody</a>
description: 生而被割，生生不息.
#creator: <a href="http://onev.cat">@onevcat</a>

#url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
 #   disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
   # weibo: yushui
    github: talaoda
   # twitter: yushui
   # gplus: 107108267983477358170
    mail: top1.vip@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
